name: 'Deploy workflow'

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: 'Deploy to Netlify'
    steps:
      - uses: actions/checkout@v3
      - uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETFLIFY_TOKEN }}
          NETLIFY_DEPLOY_TO_PROD: true